# Generated by Django 4.2.10 on 2024-02-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mail_verify_statu_user_profile_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('User', 'User'), ('Developer', 'Developer'), ('Investor', 'Investor')], default='User', max_length=50),
        ),
    ]
